# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2be30833837cf6933b209be70b8e2a0f4ff7ce5cb800bd64fa8d48b57afa2660cd4a83fa480f980b67595757cec8f55fa6115c415dbf7f3c1ae31f2d5df4d596

test:
  secret_key_base: 06bcf7e35090097fcf6a9e9ff5609485ba0d491200d2e33b1f1bcc5b8795dd5eac22a6c217c094d3f563bbbf4f0e10da96df62f2b2bf05b166e7262b362e8f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
